### ISSUE TITLE
feature request: In finding.json files add field input_data also to runtime errors

### ISSUE THREAD

**Issue by swarcojiz** [CodeIntelligenceTesting/cifuzz#421]
Tested with:
cifuzz version: 0.6.1
OS: Ubuntu 20.04
clang version: 12.0.0

When cifuzz finds an error, only the findings of type **CRASH** have the field **input_data**.
This information is very helpfull to understand what is going on to debug the bug outside of cifuzz.

So my request is, if it is possible to add this information also to findings of type **RUNTIME_ERROR**, because here 
it is sometimes hard to understand what the finding exactly is.

Here is a small example to explain this request in detail:
The code contains a runtime error in the line `MyEnum result = static_cast<MyEnum>(value);`
```
#include <cifuzz/cifuzz.h>
#include <fuzzer/FuzzedDataProvider.h>

enum MyEnum
{
    val1 = 0,
    val2 = 1
};

MyEnum convert(int value)
{
    if(value == 3)
    {
        MyEnum result = static_cast<MyEnum>(value);
        return result;
    }
    else
    {
        return MyEnum::val1;
    }
}

FUZZ_TEST_SETUP() {}

FUZZ_TEST(const uint8_t *data, size_t size) {
  FuzzedDataProvider fuzzed_data(data, size);
  int a = fuzzed_data.ConsumeIntegral<int>();

  convert(a);
}
```

The current finding.json looks like:
```
{
  "name": "upbeat_groundhog",
  "type": "RUNTIME_ERROR",
  "logs": [
    "\u001b[1m/workspaces/cifuzz_example/my_fuzz_test.cpp:9:12:\u001b[1m\u001b[31m runtime error: \u001b[1m\u001b[0m\u001b[1mload of value 3, which is not a valid value for type 'MyEnum'\u001b[1m\u001b[0m",
    "    #0 0x5578bf in convert(int) /workspaces/cifuzz_example/my_fuzz_test.cpp:9:12",
    "    #1 0x5578bf in LLVMFuzzerTestOneInputNoReturn(unsigned char const*, unsigned long) /workspaces/cifuzz_example/my_fuzz_test.cpp:21:3",
    "    #2 0x5578bf in LLVMFuzzerTestOneInput /workspaces/cifuzz_example/my_fuzz_test.cpp:17:1",
    "    #3 0x45aef1 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/workspaces/cifuzz_example/.cifuzz-build/libfuzzer/address+undefined/my_fuzz_test+0x45aef1)",
    "    #4 0x45a3fa in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/workspaces/cifuzz_example/.cifuzz-build/libfuzzer/address+undefined/my_fuzz_test+0x45a3fa)",
    "    #5 0x45c784 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector\u003cfuzzer::SizedFile, fuzzer::fuzzer_allocator\u003cfuzzer::SizedFile\u003e \u003e\u0026) (/workspaces/cifuzz_example/.cifuzz-build/libfuzzer/address+undefined/my_fuzz_test+0x45c784)",
    "    #6 0x45c999 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector\u003cfuzzer::SizedFile, fuzzer::fuzzer_allocator\u003cfuzzer::SizedFile\u003e \u003e\u0026) (/workspaces/cifuzz_example/.cifuzz-build/libfuzzer/address+undefined/my_fuzz_test+0x45c999)",
    "    #7 0x44af86 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/workspaces/cifuzz_example/.cifuzz-build/libfuzzer/address+undefined/my_fuzz_test+0x44af86)",
    "    #8 0x474ea2 in main (/workspaces/cifuzz_example/.cifuzz-build/libfuzzer/address+undefined/my_fuzz_test+0x474ea2)",
    "    #9 0x7f81a2745082 in __libc_start_main ../csu/libc-start.c:308:16",
    "    #10 0x41f6bd in _start (/workspaces/cifuzz_example/.cifuzz-build/libfuzzer/address+undefined/my_fuzz_test+0x41f6bd)",
    "",
    "SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /workspaces/cifuzz_example/my_fuzz_test.cpp:9:12 in "
  ],
  "details": "undefined behaviour: \u001b[1m\u001b[0m\u001b[1mload of value 3, which is not a valid value for type 'MyEnum'\u001b[1m\u001b[0m",
  "InputFile": "",
  "created_at": "2022-11-09T14:37:09.3157753Z",
  "stack_trace": [
    {
      "SourceFile": "my_fuzz_test.cpp",
      "Line": 9,
      "Column": 12,
      "FrameNumber": 0,
      "Function": "convert"
    },
    {
      "SourceFile": "my_fuzz_test.cpp",
      "Line": 21,
      "Column": 3,
      "FrameNumber": 1,
      "Function": "LLVMFuzzerTestOneInputNoReturn"
    }
  ]
}
```

The requested finding.json would look like:
```
{
  "name": "upbeat_groundhog",
  "type": "RUNTIME_ERROR",
  "input_data": "MgAAAQMAAIA=",
  "logs": [
    "\u001b[1m/workspaces/cifuzz_example/my_fuzz_test.cpp:9:12:\u001b[1m\u001b[31m runtime error: \u001b[1m\u001b[0m\u001b[1mload of value 3, which is not a valid value for type 'MyEnum'\u001b[1m\u001b[0m",
    "    #0 0x5578bf in convert(int) /workspaces/cifuzz_example/my_fuzz_test.cpp:9:12",
    "    #1 0x5578bf in LLVMFuzzerTestOneInputNoReturn(unsigned char const*, unsigned long) /workspaces/cifuzz_example/my_fuzz_test.cpp:21:3",
    "    #2 0x5578bf in LLVMFuzzerTestOneInput /workspaces/cifuzz_example/my_fuzz_test.cpp:17:1",
    "    #3 0x45aef1 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/workspaces/cifuzz_example/.cifuzz-build/libfuzzer/address+undefined/my_fuzz_test+0x45aef1)",
    "    #4 0x45a3fa in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/workspaces/cifuzz_example/.cifuzz-build/libfuzzer/address+undefined/my_fuzz_test+0x45a3fa)",
    "    #5 0x45c784 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector\u003cfuzzer::SizedFile, fuzzer::fuzzer_allocator\u003cfuzzer::SizedFile\u003e \u003e\u0026) (/workspaces/cifuzz_example/.cifuzz-build/libfuzzer/address+undefined/my_fuzz_test+0x45c784)",
    "    #6 0x45c999 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector\u003cfuzzer::SizedFile, fuzzer::fuzzer_allocator\u003cfuzzer::SizedFile\u003e \u003e\u0026) (/workspaces/cifuzz_example/.cifuzz-build/libfuzzer/address+undefined/my_fuzz_test+0x45c999)",
    "    #7 0x44af86 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/workspaces/cifuzz_example/.cifuzz-build/libfuzzer/address+undefined/my_fuzz_test+0x44af86)",
    "    #8 0x474ea2 in main (/workspaces/cifuzz_example/.cifuzz-build/libfuzzer/address+undefined/my_fuzz_test+0x474ea2)",
    "    #9 0x7f81a2745082 in __libc_start_main ../csu/libc-start.c:308:16",
    "    #10 0x41f6bd in _start (/workspaces/cifuzz_example/.cifuzz-build/libfuzzer/address+undefined/my_fuzz_test+0x41f6bd)",
    "",
    "SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /workspaces/cifuzz_example/my_fuzz_test.cpp:9:12 in ",
    "MS: 0 ; base unit: 0000000000000000000000000000000000000000",
    "0x32,0x0,0x0,0x1,0x3,0x0,0x0,0x80,",
    "2\\x00\\x00\\x01\\x03\\x00\\x00\\x80",
    "artifact_prefix='/tmp/libfuzzer-out-3044613779/'; Test unit written to /tmp/libfuzzer-out-3044613779/crash-03cc9d003fb19ee7bcaf3ed4419545a88ceb7359",
    "Base64: MgAAAQMAAIA="
  ],
  "details": "undefined behaviour: \u001b[1m\u001b[0m\u001b[1mload of value 3, which is not a valid value for type 'MyEnum'\u001b[1m\u001b[0m",
  "InputFile": "",
  "created_at": "2022-11-09T14:37:09.3157753Z",
  "stack_trace": [
    {
      "SourceFile": "my_fuzz_test.cpp",
      "Line": 9,
      "Column": 12,
      "FrameNumber": 0,
      "Function": "convert"
    },
    {
      "SourceFile": "my_fuzz_test.cpp",
      "Line": 21,
      "Column": 3,
      "FrameNumber": 1,
      "Function": "LLVMFuzzerTestOneInputNoReturn"
    }
  ]
}
```

**Comment by adombeck** [comment]
Findings of the UndefinedBehaviorSanitizer should be stored with the crashing input by default. Only if you use the `--recover-ubsan` flag, those findings are expected to be stored without a crashing input. Do you use that flag or the corresponding option in the `cifuzz.yaml`?

**Comment by swarcojiz** [comment]
Thanks for your fast reply.

Yes accidentially I have enabled this flag. And now I have seen in the comment of this flag,
that then the crashing input data will not be add to the findings.

But would it be possible to add the input data to the findings, when this flag is enabled?
Because it would be very nice, when several undefined behaviours are found until a crash appears.

**Comment by adombeck** [comment]
> But would it be possible to add the input data to the findings, when this flag is enabled?

Unfortunately, there is currently no way to get the input that triggered a finding from libFuzzer unless the finding is fatal.

**Comment by swarcojiz** [comment]
Ok, thank you for the explanation.
